# Generated by Django 3.1.7 on 2021-04-28 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='freeDemoRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150, null=True)),
                ('phone_no', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FullCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(default='null', max_length=800)),
                ('fee', models.FloatField()),
                ('thumbnail', models.FileField(upload_to='courseThumbnail/')),
                ('live_one_to_one', models.BooleanField(default=False)),
                ('self_paced', models.BooleanField(default=False)),
                ('offline', models.BooleanField(default=False)),
                ('next_batch_starting_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MiniCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=1000)),
                ('fee', models.FloatField()),
                ('thumbnail', models.FileField(upload_to='course_thumbnail/')),
                ('syllabus', models.FileField(upload_to='course_syllabus/')),
                ('course_preview_video', models.FileField(null=True, upload_to='course_preview_videos/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('live_one_to_one', models.BooleanField(default=False)),
                ('self_paced', models.BooleanField(default=False)),
                ('offline', models.BooleanField(default=False)),
                ('next_batch_starting_date', models.DateField(null=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='moreAboutPdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('pdf', models.FileField(upload_to='know_more_pdf/')),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150, null=True)),
                ('phone_no', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('specialized_in', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='UserMiniCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=100)),
                ('paid', models.BooleanField(default=False)),
                ('mini_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduPlatform.minicourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFullCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=100)),
                ('full_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduPlatform.fullcourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('duration_in_hours', models.IntegerField()),
                ('class_link', models.CharField(max_length=1000)),
                ('mini_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduPlatform.minicourse')),
            ],
        ),
        migrations.CreateModel(
            name='SyllabusDownloadData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150, null=True)),
                ('phone_no', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('mini_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eduPlatform.minicourse')),
            ],
        ),
        migrations.CreateModel(
            name='MiniCoursesInFullCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduPlatform.fullcourse')),
                ('mini_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduPlatform.minicourse')),
            ],
        ),
        migrations.CreateModel(
            name='MiniCourseRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_given', models.IntegerField(choices=[(5, 5), (4, 4), (3, 3), (2, 2), (1, 1)], default=0)),
                ('mini_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduPlatform.minicourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FullCourseRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_given', models.IntegerField(choices=[(5, 5), (4, 4), (3, 3), (2, 2), (1, 1)], default=0)),
                ('full_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduPlatform.fullcourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
