# Generated by Django 3.1.7 on 2021-04-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduPlatform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfullcourse',
            name='phone_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userminicourse',
            name='phone_no',
            field=models.IntegerField(default=0),
        ),
    ]
