# Generated by Django 3.1.7 on 2021-04-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduPlatform', '0002_auto_20210429_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfullcourse',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
