# Generated by Django 3.1.7 on 2021-04-30 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eduPlatform', '0003_userfullcourse_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userminicourse',
            name='mini_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eduPlatform.minicourse'),
        ),
        migrations.AlterField(
            model_name='userminicourse',
            name='mode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userminicourse',
            name='paid',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='userminicourse',
            name='phone_no',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userminicourse',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
