# Generated by Django 3.1.7 on 2021-05-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduPlatform', '0006_fullcourse_course_preview_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='lecture_video',
            field=models.FileField(null=True, upload_to='courseTutorials/<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='class_link',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
