# Generated by Django 3.1.7 on 2021-05-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduPlatform', '0007_auto_20210501_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='lecture_video',
            field=models.FileField(null=True, upload_to='courseTutorials/'),
        ),
    ]
