# Generated by Django 3.1.7 on 2021-05-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduPlatform', '0009_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='person_by',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
