# Generated by Django 3.1.7 on 2021-05-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduPlatform', '0010_auto_20210510_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='person_by',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
