# Generated by Django 3.1.7 on 2021-05-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduPlatform', '0011_auto_20210510_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='fullcourse',
            name='high_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='minicourse',
            name='high_price',
            field=models.FloatField(default=0),
        ),
    ]
