# Generated by Django 3.1.7 on 2021-05-31 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduPlatform', '0017_auto_20210529_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullcourserating',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minicourserating',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
