# Generated by Django 3.1.7 on 2021-05-31 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduPlatform', '0018_auto_20210531_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='minicourse',
            name='class_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
