# Generated by Django 2.2.14 on 2021-08-04 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduPlatform', '0021_auto_20210804_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='add_blocks',
        ),
        migrations.AddField(
            model_name='blogs',
            name='add1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogs',
            name='add2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogs',
            name='add3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogs',
            name='desc1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='desc2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='desc3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='img1',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='blogs',
            name='img2',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='blogs',
            name='img3',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
