# Generated by Django 2.2.14 on 2021-08-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduPlatform', '0023_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='add1',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='add2',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='add3',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='desc1',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='desc2',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='desc3',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='img3',
        ),
        migrations.AddField(
            model_name='blogs',
            name='add',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2),
        ),
    ]
