# Generated by Django 2.2.14 on 2021-08-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduPlatform', '0024_auto_20210804_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='add',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], default='0', max_length=2),
        ),
    ]
