# Generated by Django 2.2.14 on 2021-08-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduPlatform', '0027_auto_20210804_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='img',
        ),
        migrations.AddField(
            model_name='blog',
            name='desc5',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='img5',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
