# Generated by Django 2.2.14 on 2021-08-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduPlatform', '0029_auto_20210804_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.TextField(default='Unamed', null=True),
        ),
    ]
