# Generated by Django 2.2.14 on 2021-08-04 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduPlatform', '0030_auto_20210804_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='title',
        ),
    ]
