# Generated by Django 2.2.14 on 2021-08-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduPlatform', '0037_auto_20210806_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='post_views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
