# Generated by Django 2.2.14 on 2021-08-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduPlatform', '0040_auto_20210806_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ManyToManyField(default='C Programming', to='eduPlatform.Blogcategory'),
        ),
    ]
