# Generated by Django 2.2.14 on 2021-08-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduPlatform', '0041_blog_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDevelopmentCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=1000)),
                ('fee', models.FloatField()),
                ('thumbnail', models.FileField(upload_to='course_thumbnail/')),
                ('syllabus', models.FileField(upload_to='course_syllabus/')),
                ('course_preview_video', models.FileField(null=True, upload_to='course_preview_videos/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('live_one_to_one', models.BooleanField(default=False)),
                ('self_paced', models.BooleanField(default=False)),
                ('offline', models.BooleanField(default=False)),
                ('inoffice', models.BooleanField(default=False)),
                ('next_batch_starting_date', models.DateField(null=True)),
                ('high_price', models.FloatField(default=0)),
                ('class_link', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
