# Generated by Django 2.2.14 on 2021-08-18 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eduPlatform', '0045_pdptopic'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDevelopmentCoursesInFullCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduPlatform.FullCourse')),
                ('pdp_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduPlatform.MiniCourse')),
            ],
        ),
    ]
