# Generated by Django 2.2.14 on 2021-08-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduPlatform', '0046_personaldevelopmentcoursesinfullcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Un-Named', max_length=80)),
                ('link', models.TextField(blank=True)),
            ],
        ),
    ]
