# Generated by Django 2.2.14 on 2021-08-19 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduPlatform', '0047_youtubevideos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YoutubeVideos',
            new_name='YoutubeVideo',
        ),
    ]
