# Generated by Django 2.2.14 on 2021-08-21 09:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eduPlatform', '0050_carousselimage_studentreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousselimage',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
