# Generated by Django 2.2.14 on 2021-08-21 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduPlatform', '0051_carousselimage_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarousselImage',
        ),
        migrations.DeleteModel(
            name='StudentReview',
        ),
    ]
