# Generated by Django 2.2.14 on 2021-08-25 09:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eduPlatform', '0052_auto_20210821_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='person_by',
            new_name='speaker',
        ),
        migrations.RemoveField(
            model_name='event',
            name='link',
        ),
        migrations.RemoveField(
            model_name='event',
            name='registrationForm_link',
        ),
        migrations.AddField(
            model_name='event',
            name='about_speaker',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='event_posters/'),
        ),
    ]
