# Generated by Django 2.2.14 on 2021-08-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduPlatform', '0053_auto_20210825_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='post_views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
