# Generated by Django 2.2.14 on 2021-08-25 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduPlatform', '0055_event_iamge_speakerm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='iamge_speakerm',
            new_name='image_speaker',
        ),
    ]
