# Generated by Django 2.2.14 on 2021-08-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduPlatform', '0059_eventregistration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
