# Generated by Django 2.2.14 on 2021-08-31 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduPlatform', '0062_auto_20210831_1132'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeacherProfile',
            new_name='Teacher_Profile',
        ),
    ]
