# Generated by Django 2.2.14 on 2021-08-31 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eduPlatform', '0063_auto_20210831_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150, null=True)),
                ('image', models.ImageField(upload_to='teacherimages/')),
                ('phone_no', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduPlatform.FullCourse')),
            ],
        ),
        migrations.DeleteModel(
            name='Teacher_Profile',
        ),
    ]
