# Generated by Django 2.2.14 on 2021-08-31 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduPlatform', '0064_auto_20210831_1134'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teachers_Profile',
            new_name='TeacherProfile',
        ),
    ]
